export { default as Home } from "./home";
export { default as Artist } from "./artist";
export { default as Music } from "./music";
export { default as Video } from "./video";
export { default as Event } from "./event";
export { default as Contact } from "./contact";
export { default as Blog } from "./blogs";
export { default as BlogDetail } from "./blog_detail";
export { default as VideoDetail } from "./video_detail";
